JBJCA-1362 NPE from SemaphoreConcurrentLinkedDequeManagedConnectionPo…
ironjacamar/ironjacamar pull request #751
Opened 2022-05-06 12:13 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/JBJCA-1362

2022-05-10 08:14 UTC, tadamski requested changes
LGTM but why this unusual tracef text formatting?

2022-05-12 07:03 UTC, RanabirChakraborty commented
Thanks! @tadamski changed it accordingly.

2022-05-12 16:17 UTC, tadamski commented
@RanabirChakraborty thanks; merging

2022-05-12 16:17 UTC, tadamski approved these changes

2022-05-12 16:18 UTC, merged